
USE project;
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Oktoberfest", "Festival Beer", "A full bodied, malty, slightly sweet beer celebrating the Autumn harvest. This rich beer has a round malt flavor and an above average alcohol content perfect for a cool fall evening.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Art Car", "IPA", "The nose is a blend of apricot and tropical fruit and mango. The taste starts with a big bitter blood orange that morphs into mangos and sweet tropical fruits. There is a lightly sweet malt body that allows the hops to shine while maintaining a nice complexity to the flavors.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Elissa", "IPA", "A traditional India Pale Ale, the Elissa IPA is very hoppy with a properly balanced malty body. Elissa has huge hop additions in the kettle that give it a wonderful bitterness and is then dry-hopped in the fermenter to create the pleasant floral, hoppy nose. Our reverse osmosis water makes the bitter very soft with no harsh notes to it. The maltiness is derived from British Maris Otter malt.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Fancy Lawnmover", "German-Style Kolsch", "A true German-style Kölsch. Originally brewed in Cologne, this beer is crisp and refreshing, yet has a sweet malty body that is balanced by a complex, citrus hop character. Multiple additions of German Hallertauer hops are used to achieve this delicate flavor. We use a special Kölsch yeast, an ale yeast that ferments at lager temperatures, to yield the slightly fruity, clean flavor of this beer. Fancy Lawnmower Beer is a world class brew yet light enough to be enjoyed by Texans after strenuous activities, like mowing the lawn.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Daydream", "Session", "Daydream is a bright American saison with American hops and Belgian yeast. It has a floral and fruity aroma with quite a bit of citrus and tropical fruit notes. It has a slight breadiness from the malt, a spicy and fruity Belgian yeast character, and a nice citrus hop flavor. Its dry finish invites you in for another sip.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Santo", "Black Kolsch", "Santo is a black Kölsch, which technically doesn’t exist as a style, but this is as close as we can come to describing it. Essentially it is brewed using a Kölsch recipe with the addition of Munich and black malt. It is light bodied and floral yet with a distinct dark malt flavor. Our goal was to create a dark yet refreshing beer that would pair perfectly with a plate of enchiladas.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Orange Show", "Blonde Ale", "A blonde ale with real blood oranges. A strong citrus aroma comes from blood orange purée added during fermentation and the choice of citrusy hops. The combination of sweet, bitter and slightly tart flavors make it a balanced, light bodied beer.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("5 O'Clock Pils", "Lager", "We believe the greatest beers are the ones that achieve their goal with the simplest recipes. 5 O'Clock Pils is all about its two ingredients: pils malt and Saaz hops. This is the entire basis of the original Bohemian Pils style. The pils malt is light yet with a pleasant bready character, emphasized by the decoction mash wherein a portion of the mash is removed, boiled and added back. Saaz hops, the only hop that has never been hybridized dating back to when it was first cultivated from a wild plant around 1,000 years ago, gives a pleasant earthy spiciness. The final beer has a light maltiness, a big refreshing bitter and wonderful, delicate hop flavor and aroma. This is the beer we enjoy every year in the Czech Republic when doing our Saaz hop selection. Only, we've added even more hops. It is a beer that can be enjoyed everyday of the year. You will never tire of it.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Amber Ale", "Ale", "A well balanced, full flavored, amber ale. It has a rich, malty body with a pleasant caramel character derived from a specialty Caravienne malt. A complex hop aroma, with a hint of floral and citrus comes from a combination of Cascades and Liberty hops. It has a rich, creamy head with a fine lace. The light fruitiness, characteristic of ales, is derived from a proprietary yeast strain.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Ale Wagger", "Ale", "A beautiful, deep copper brown ale. It has a full, malty body with hints of chocolate, a touch of sweetness and a light hop flavor. A complex malt character is created by combining five different types of malts. It has a rich, creamy head with a fine lace. The light fruitiness, characteristic of ales, is derived from a proprietary yeast strain.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Guten Tag", "Bavarian-Style Lager", "Guten Tag is a traditional Bavarian-style lager with a crisp and clean flavor. The malt provides a nice toasty and bready complexity through the use of decoction, while the hops are restrained to allow a soft and elegant finish.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Pub Crawl", "Pale Ale", "This crisp, sessionable Pale Ale is brewed with a combination of hops: Centennial hops at the beginning of the boil for bitterness, and Amarillo and Galaxy hops at the end for the bulk of the flavor and aroma. Two Row Pale and Maris Otter English Pale malts give the beer a slight color and tiny amount of sweetness. Golden naked oats malt lend a nutty, more full-bodied flavor, and the London III yeast accentuates the hop flavor and aroma.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Citrodos", "IPA", "Citrodos IPA is an American IPA with lower ABV and IBU than typical of the style. It has a glowing golden hue with off-white head that lingers through the glass. The aroma has pronounced citrus and tropical fruit notes. The hop flavor from the Citra and Centennial hops begins with orange and grapefruit character, with a honeydew finish balanced by a graham cracker malt sweetness. Citrodos IPA finishes clean and dry.", "Saint Arnold");
INSERT INTO beers (beer_name, beer_type, beer_description, brewrey) VALUES ("Raspberry AF", "Berliner Weisse", "Raspberry AF is a fruited Berliner Weisse. It is a light bodied but surprisingly flavorful sour wheat beer brewed with lots and lots of real raspberry. The flavor is an upfront, thirst quenching raspberry delight, followed by a tart and dry finish, making your palate thirst for more.", "Saint Arnold");

